#spring-datasource
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/database1?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: mysql
    type: com.alibaba.druid.pool.DruidDataSource
#mybatis-plus
mybatis-plus:
  mapper-locations: classpath*:mybatis/mappers/*.xml
  type-aliases-package: com.staticzz.entity
#server
server:
  port: 80
  servlet:
    context-path: /staticzz
#shiro-redis
shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379
#jwt
com:
  staticzz:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization